apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "marksun2020/capstone"
        ports:
        - containerPort: 80 
