apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  replicas: 1
  selector:
    app: capstoneproject
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
