apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstoneproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstoneproject
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
      - name: app
        image: "marksun2020/capstone"
        ports:
        - containerPort: 80 
